Use realpaths for better portability

diff --git a/bin/loco b/bin/loco
--- a/bin/loco
+++ b/bin/loco
@@ -1,4 +1,91 @@
 #!/usr/bin/env bash
+readonly __bpkr_packed=yes
+{ if [[ $OSTYPE != cygwin && -e /dev/fd/0 ]]; then source /dev/fd/0; else source <(cat); fi; } <<'# --- END d6702cbd7094e6332817ae73643e630ce97c687d8e0e0e9e7f6ad62eda062d7f ---'
+if [[ ${BASHPACKR_LOADED-} != *\<bashpackr\>* ]]; then BASHPACKR_LOADED+=\<bashpackr\>
+import:()      { is-imported: "$1" || bpkr.__fatal "module '$1' wasn't packed"; }
+main:()        { if [[ $0 == ${BASH_SOURCE[1]} ]]; then "$@"; exit $?; fi; }
+pack-with:()   { :; }  # No-op at runtime of packed scripts
+can-import:()  { is-imported: "$1"; }  # can't import what isn't packed
+is-imported:() { [[ ${BASHPACKR_LOADED-} == *"<$1>"* ]]; }
+bpkr.__fatal() { echo "bashpackr: fatal error: " "$1" >&2; exit ${2-70}; }
+fi
+if [[ ${BASHPACKR_LOADED-} != *\<realpaths\>* ]]; then BASHPACKR_LOADED+=\<realpaths\>
+#!/usr/bin/env bash
+
+realpath.location()  { realpath.follow "$1"; realpath.absolute "$REPLY" ".."; }
+realpath.resolved()  { realpath.follow "$1"; realpath.absolute "$REPLY"; }
+
+realpath.follow() {
+    local target
+    while [[ -L "$1" ]] && target=$(readlink -- "$1"); do
+        realpath.dirname "$1"
+        # Resolve symlink target relative to symlink's directory
+        [[ $REPLY != . && $target != /* ]] && REPLY=$REPLY/$target || REPLY=$target
+        # Break out if we found a symlink loop
+        for target; do [[ $REPLY == "$target" ]] && break 2; done
+        # Add current result to the loop-detect list and tail-recurse
+        set -- "$REPLY" "$@"
+    done
+    REPLY="$1"
+}
+
+
+realpath.absolute() {
+    set -- "$PWD" "$@"
+    while (($#>1)); do
+        case $2 in
+        /*) shift ;;                        # absolute paths don't get prefixed
+        *)  set -- "${1%/}/$2" "${@:3}" ;;  # join everything else
+        esac
+    done
+    IFS=/ eval 'set -- $1'    # normalize the path by splitting on /
+    set -- "${1:-/}" "${@:2}"   # and ensuring first element is a /
+    while (($#>1)); do
+        case $2 in
+        ''|.)  set -- "$1" "${@:3}" ;;  # no-op path
+        ..) realpath.dirname "$1"; set -- "$REPLY" "${@:3}" ;;
+        *)  set -- "${1%/}${2:+/$2}" "${@:3}" ;;
+        esac
+    done
+    REPLY="$1"
+}
+
+
+realpath.dirname() {
+    while [[ $1 == *?/ ]]; do set -- "${1%/}"; done         # strip ending /
+    REPLY="${1%/*}"                                         # remove basename
+    [[ $REPLY == "$1" ]] && REPLY=. || REPLY=${REPLY:-/}    # handle . and /
+    while [[ $REPLY == *?/ ]]; do REPLY=${REPLY%/}; done    # strip ending /
+}
+
+realpath.basename() {
+    while [[ $1 == *?/ ]]; do set -- "${1%/}"; done
+    REPLY="${1##*/}"; if [[ "$1"  && ! "$REPLY" ]]; then REPLY=/; fi
+}
+
+
+realpath.canonical() {
+    local target=""
+    realpath.follow "$1"; set -- "$REPLY"   # $1 is now resolved
+    realpath.basename "$1"; target=$REPLY   # target = basename $1
+    realpath.dirname "$1";
+    [[ $REPLY != "$1" ]] && realpath.canonical "$REPLY"; # recurse unless root
+    realpath.absolute "$REPLY" "$target";   # combine canon parent w/basename
+}
+
+realpath.relative() {
+    local target=""
+    realpath.absolute "$1"; set -- "$REPLY" "${@:2}"; realpath.absolute "${2-$PWD}" X
+    while realpath.dirname "$REPLY"; [[ "$1" != "$REPLY" && "$1" == "${1#${REPLY%/}/}" ]]; do
+        target=../$target
+    done
+    [[ $1 == "$REPLY" ]] && REPLY=${target%/} || REPLY="$target${1#${REPLY%/}/}"
+    REPLY=${REPLY:-.}
+}
+
+fi
+# --- END d6702cbd7094e6332817ae73643e630ce97c687d8e0e0e9e7f6ad62eda062d7f ---
+#!/usr/bin/env bashpackr
 
 # LICENSE
 # -------
@@ -51,12 +138,12 @@ print_if_exists() {
     for f in ${@:1:${#}-1}; do [[ -f "$f" ]] && echo "${d%/}/$f" && return 0; done
     return 1
 }
-
+import: realpaths
 walkup() {
-    local d="$(realpath "$1")"
+    realpath.resolved "$1"; local d="$REPLY"
     until "${@:2}" "$d"; do
         [[ "$d" != "/" ]] || return 1
-        d="$(dirname "$d")"
+        realpath.dirname "$d"; d="$REPLY"
     done
 }
 
